import { Campaign } from './types';

// Map niches to image paths - use the first primary niche
const getImageForNiches = (niches: string[]): string => {
  const nicheToImage: Record<string, string> = {
    'Investing': 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/financial-mhZresd0sPk082ItzczpYkKP6yce4A.jpg',
    'Crypto': 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/cyber-5lmSGnVOriys4RNkgwKLvIayifotJv.jpg',
    'Web3': 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Web3-R5gXiPaCmxB3GKC1qItsksM1nBwInK.jpg',
    'AI': 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/SaaS-qXyjfVeAnCAUkRqhbXtJwFSzT0Dqf2.jpg',
    'Gaming': 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/gaming-bOXeL0xZdu77gRBlp29AkbuHVoSzsJ.jpg',
    'SaaS': 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/SaaS-qXyjfVeAnCAUkRqhbXtJwFSzT0Dqf2.jpg',
    'Healthcare': 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/healthcare-zrUIIAbfC4ZOvWZhdxHQrRdJpyySfc.jpg',
    'Education': 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/education-tKjTTU1ae7Q8Tm8nsKAHxmKXep5Th4.jpg',
  };
  
  // Return image for first niche, fallback to SaaS
  return nicheToImage[niches[0]] || nicheToImage['SaaS'];
};

export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    title: 'Strategic Investing Platform',
    description: 'AI-powered investment platform with advanced analytics and market insights',
    imageUrl: getImageForNiches(['Investing', 'Crypto', 'Web3']),
    budget: 300,
    maxBudget: 10000,
    views: 10000,
    niches: ['Investing', 'Crypto', 'Web3'],
    budgetUsedPercent: 20,
    popularityRating: 85,
    publishedDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    budgetHistory: [
      { percent: 15, date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 18, date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 20, date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    title: 'Decentralized Crypto Future',
    description: 'Revolutionary crypto platform combining DeFi with gaming mechanics',
    imageUrl: getImageForNiches(['Crypto', 'Web3']),
    budget: 300,
    maxBudget: 10000,
    views: 10000,
    niches: ['Crypto', 'Web3'],
    budgetUsedPercent: 20,
    popularityRating: 92,
    publishedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    budgetHistory: [
      { percent: 22, date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 21, date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 20, date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    title: 'Power of Web3',
    description: 'Complete Web3 infrastructure and tools for decentralized applications',
    imageUrl: getImageForNiches(['Web3', 'Crypto']),
    budget: 300,
    maxBudget: 10000,
    views: 10000,
    niches: ['Web3', 'Crypto'],
    budgetUsedPercent: 20,
    popularityRating: 78,
    publishedDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    budgetHistory: [
      { percent: 25, date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 23, date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 20, date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    title: 'AI Trading Bot Revolution',
    description: 'Next-generation AI-powered trading system with machine learning',
    imageUrl: getImageForNiches(['AI', 'Investing']),
    budget: 500,
    maxBudget: 15000,
    views: 8500,
    niches: ['AI', 'Investing', 'Crypto'],
    budgetUsedPercent: 35,
    popularityRating: 95,
    publishedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    budgetHistory: [
      { percent: 30, date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 33, date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 35, date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    title: 'Next-Gen Gaming',
    description: 'Community-driven gaming guild for blockchain-based games',
    imageUrl: getImageForNiches(['Gaming', 'Web3']),
    budget: 250,
    maxBudget: 8000,
    views: 9200,
    niches: ['Gaming', 'Web3', 'Crypto'],
    budgetUsedPercent: 28,
    popularityRating: 88,
    publishedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    budgetHistory: [
      { percent: 28, date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 28, date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 28, date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    title: 'Future of Healthcare',
    description: 'AI-powered diagnostic system for medical professionals',
    imageUrl: getImageForNiches(['Healthcare', 'AI']),
    budget: 750,
    maxBudget: 20000,
    views: 12500,
    niches: ['Healthcare', 'AI', 'SaaS'],
    budgetUsedPercent: 42,
    popularityRating: 90,
    publishedDate: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    budgetHistory: [
      { percent: 38, date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 40, date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 42, date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    title: 'Education Reimagined',
    description: 'Online learning platform with interactive courses and AI tutoring',
    imageUrl: getImageForNiches(['Education', 'AI']),
    budget: 400,
    maxBudget: 12000,
    views: 7800,
    niches: ['Education', 'SaaS', 'AI'],
    budgetUsedPercent: 32,
    popularityRating: 82,
    publishedDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    budgetHistory: [
      { percent: 35, date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 34, date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 32, date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '8',
    title: 'Scalable SaaS Solutions',
    description: 'Enterprise-grade SaaS platform for business automation',
    imageUrl: getImageForNiches(['SaaS', 'AI']),
    budget: 600,
    maxBudget: 18000,
    views: 11200,
    niches: ['SaaS', 'Web3', 'Investing'],
    budgetUsedPercent: 38,
    popularityRating: 87,
    publishedDate: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    budgetHistory: [
      { percent: 35, date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 36, date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 38, date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '9',
    title: 'Web3 Gaming Ecosystem',
    description: 'Next-gen NFT trading platform with advanced features',
    imageUrl: getImageForNiches(['Web3', 'Gaming']),
    budget: 450,
    maxBudget: 14000,
    views: 9900,
    niches: ['Web3', 'Crypto', 'Gaming'],
    budgetUsedPercent: 30,
    popularityRating: 91,
    publishedDate: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    budgetHistory: [
      { percent: 30, date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 30, date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
      { percent: 30, date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    ],
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
